In [1]:
from kmeans import kmeans_equal
import torch

In [4]:
N = 100
batch_size = 1
num_clusters = 10

cluster_size = N // num_clusters
X = torch.randn(batch_size, N, 3)
choices, centers = kmeans_equal(X, num_clusters, cluster_size)

tensor([[[ 0.3250,  0.0429, -0.2722],
         [-0.4589,  0.4501,  0.4760],
         [-0.2756,  0.2877,  0.0705],
         [-0.0959, -0.0341,  0.3591],
         [ 0.1032,  0.2723,  0.3530],
         [-0.1250,  0.0285,  0.0514],
         [ 0.0013, -0.0967, -0.0962],
         [ 0.1272,  0.3941, -0.1983],
         [ 0.2847, -0.0939, -0.0413],
         [-0.3415, -0.2899,  0.0939]]])


In [9]:
# print counts of choices[0]
print(choices[0].bincount(minlength=num_clusters))

tensor([39,  0,  0,  0,  2, 49,  0,  0,  0, 10])


In [10]:
choices[0]

tensor([9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 5, 0, 5, 0, 5, 0, 5, 5, 5, 0, 5, 5, 0, 5,
        0, 5, 5, 5, 0, 0, 5, 5, 0, 0, 0, 0, 5, 5, 0, 5, 5, 5, 5, 0, 5, 5, 5, 0,
        0, 0, 5, 0, 5, 5, 5, 0, 0, 5, 5, 0, 0, 5, 0, 5, 0, 5, 0, 5, 5, 5, 0, 0,
        5, 5, 5, 0, 5, 0, 0, 5, 0, 0, 5, 0, 0, 5, 0, 0, 0, 5, 5, 0, 0, 5, 5, 5,
        5, 4, 4, 5])